# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 3.0
  beta: 8.0 

learning_rate:
  text: 0.0005
  image: 0.0005
  align: 0.5

alpha: [ 3 ]

alpha1 : [0.5,0.5]

epoch: [0.000001, 0.002]

belta : [ 2.5]