# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 8.0
  beta: 5.0 



learning_rate:
  text: 0.0002
  image: 0.0001
  align: 0.2

alpha: [ 2.5 ]

alpha1: [0,0.5]

epoch: [1e-7,1e-7]

belta : [ 2 ]