# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 4.0
  beta: 7.0 

learning_rate:
  text: 0.0001
  image: 0.00005
  align: 0.3

alpha: [ 1.8 ]

epoch: [0.000001,0.000001]

alpha1: [0,0]
belta: [ 1.0]