# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 3.0
  beta: 7.0 

learning_rate:
  text: 0.0001
  image: 0.0001
  align: 1.5

alpha: [ 3.3 ]

alpha1: [ 0.5 ,0.5]

epoch : [0.005, 0.01]

belta: [ 3.2]