# Configuration for DPE Hyperparameters

# --- Positive Cache Configuration ---
positive:
  enabled: True
  shot_capacity: 3
  alpha: 9.0
  beta: 8.0 

learning_rate:
  text: 0.0004
  image: 0.0004
  align: 0.2

alpha: [ 2.7 ]

alpha1: [ 0.5,0.5 ]

epoch : [1e-7, 1e-7]

belta: [ 3 ]